### ISSUE TITLE
Do you know about createrepo?

### ISSUE THREAD

**Issue by steven3363** [mihawk90/obs-studio.spec#2]
You can create your own repo using createrepo. 
These can be added as a DNF repo.

If you need any help I can host (have my ownwebserver) supply a domian I can set up. And give you control of the site.

**Comment by mihawk90** [comment]
I know about it, but I have not looked into it much because I don't have a webserver to host on.

I thank you for the offer, however (and please don't take this personally), I don't really feel comfortable hosting on someone else's (private) infrastructures/domains.

I have looked into a couple possibilites, but I haven't decided on what to do yet.

**Comment by korewaChino** [comment]
I actually hosted your RPM on Copr, and my own repo for my Fedora remix actually, so...

**Comment by mihawk90** [comment]
I know that it's possible to host on COPR in a technical sense (i.e. it builds), however back when I started out with this, I asked on the IRC whether it would be possible from a licensing standpoint and what I was told is that essentially most projects requiring RPM Fusion to build (specifically for x264 and ffmpeg in this case) would technically not be allowed on it due to the Fedora packaging guidelines.
Bundling CEF was another issue but I was told it wouldn't be as much of a problem licensing wise.

So yeah, I know it's possible, but licensing wise it's complicated.

**Comment by korewaChino** [comment]
I know, it's legally impossible to host OBS on Copr but I did it anyway lol. I mirrored it on my Koji instance in case they take it down.

**Comment by mihawk90** [comment]
As per [28.0.2-11](https://github.com/mihawk90/obs-studio.spec/releases/tag/v28.0.2-11) there is now a Packagecloud repo. Although this does have a monthly bandwidth limit, going by the past Github release download numbers that shouldn't be a big issue for a while.
