### ISSUE TITLE
28.0 Release Candidate RPM?

### ISSUE THREAD

**Issue by 3laws** [mihawk90/obs-studio.spec#3]
Yeah, just the title. Will this git stay updated for release candidates or just final releases? 

I'm having one heck of struggle to build from source and I was hoping to see RC's here.

**Comment by mihawk90** [comment]
I was planning on it yea, but unfortunately didn't find the time yet.

There were a lot of changes so it's going to take a while, might just end up only being the final release, we'll see.

Sorry about that, just stuff going on.

**Comment by 3laws** [comment]
Looking forward to it, whichever version it ends being. I understand, life happens.

Also, do you have success building following the instructions in their Wiki? I have never been able too and my github issues always stay unresolved. Any tips/insight?

**Comment by mihawk90** [comment]
Finally got around to this, so here you go:
https://github.com/mihawk90/obs-studio.spec/releases/tag/v28.0.2-11

> Also, do you have success building following the instructions in their Wiki?

I hadn't tried until now and I haven't looked at the WIki for a while to be honest. Most of the work is done by RPM Fusion anyway and I just add the parts that they don't ship.

In the past I had updated the Wiki every now and then when there were dependencies missing but that was before 28.

> I have never been able too and my github issues always stay unresolved. Any tips/insight?

If you're having issues with compilation, the OBS discord is probably a good place to start. The GitHub issues are only used for actual bugs and not support requests. Since OBS does compile, it's not considered a bug and therefore closed.

Anyway, closing this as resolved with the release.

**Comment by 3laws** [comment]
Thanks, in the meantime I had success building from source (figuring out missing dependencies on the go) and have been rocking the portable version (since the native seems to ignore any python3 version higher then the recommended).

I missed your RPM since I use the Twitch integration + BetterTTV emotes and I hadn't got the the length of properly configuring Twitch API to get the proper IDs and hashes.

I'm however in 37 now and looks like I'll have to wait a little longer. Really appreciate this tho, looking forward for it in a few days.

Hope life is good.

**Comment by mihawk90** [comment]
> I'm however in 37 now and looks like I'll have to wait a little longer. Really appreciate this tho, looking forward for it in a few days.

Yeah the git for the Mock files is already updated, so it's just going through processes now. Shouldn't be more then a week normally until the package hits the repo.



> Hope life is good.

All's good, thanks 🙂 just had a bit of stress for a couple weeks, nothing that can't be handled tho

> configuring Twitch API to get the proper IDs and hashes

The OBS teams' IDs and hashes aren't public anyway and if you get your own you'd also need to host your own OAuth backend. Of course that's doable but not really viable for just a private build.

**Comment by mihawk90** [comment]
Release updated with F37 RPMs.

Realised I was dumb and remembered I could just download the mock rpm off the RPM Fusion `updates-testing` repo :)
