### ISSUE TITLE
Can't install (nothing provides qt5-qtbase(x86-64) = 5.15.5)

### ISSUE THREAD

**Issue by puyoxyz** [mihawk90/obs-studio.spec#4]
Hi, I'm trying to install the latest update (28.0.2) but getting this error:

```
 Problem: package obs-studio-28.0.2-11.fc36.x86_64 requires obs-studio-libs(x86-64) = 28.0.2-11.fc36, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides qt5-qtbase(x86-64) = 5.15.5 needed by obs-studio-libs-28.0.2-11.fc36.x86_64
============================================================================================================================================================
 Package                                Architecture                  Version                               Repository                                 Size
============================================================================================================================================================
Skipping packages with broken dependencies:
 obs-studio                             x86_64                        28.0.2-11.fc36                        tarulia_obs-studio                        4.2 M
 obs-studio-libs                        x86_64                        28.0.2-11.fc36                        tarulia_obs-studio                         89 M

Transaction Summary
============================================================================================================================================================
Skip  2 Packages

Nothing to do.
Complete!
```

Seems that the only versions of qt5-qtbase available in repos are 5.15.3 and 5.15.6 (and not 5.15.5)?

I tried to use rpmrebuild to rebuild obs-studio-libs and change it to 5.15.6 but it doesn't work (complains about missing files)

**Comment by mihawk90** [comment]
huh... that's weird.
I assume you are actually on F36? Not running F37 beta?

I'm on F36 myself and it installed just fine 🤔 
I'd have to check when I get back home

What is `dnf info qt5-qtbase --refresh --showduplicates` giving you?

edit: ~~I don't get why it's nailing the dependency on 5.15.5 since the spec doesn't even specify a version at all 🤔~~ Nevermind, [I'm blind](https://github.com/mihawk90/obs-studio.spec/blob/2ba1b5f70f3a55c4a2183e82af5c2d73f5e18ec8/obs-studio.spec#L93)

Also curious can you install OBS Studio from RPM Fusion?

> I tried to use rpmrebuild to rebuild obs-studio-libs and change it to 5.15.6 but it doesn't work (complains about missing files)

Yeah I don't upload the .src.rpm because 1. I feel there's little point to it and 2. I don't want to leak OBS' ClientIDs and hashes for Twitch, Restream, and YouTube. You can also disable the source repo (and I'd also advise changing the cache timeout of the repo because the default 5 minutes is crazy low).

---

I have an idea where it's coming from though. I uploaded the packages on the 25th, RPM Fusion pushed their update on the 26th and it might be that the Qt update was just between that... so yeah. Might have to rebuild the RPMs when I get home.

**Comment by mihawk90** [comment]
So, home now and yes apparently there was a Qt update in between... oh well.

Building now, uploading soon-ish
